// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dumddgtlebbosmszomvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1bWRkZ3RsZWJib3Ntc3pvbXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTQ2NjEsImV4cCI6MjA2NDY5MDY2MX0.vUZAa1TojwMAPQ-DwohVtumal4K12F97NmKHj6osAIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);